### ISSUE TITLE
Icon search

### ISSUE THREAD

**Issue by work-leonid** [owaiswiz/tabler_icons_ruby#1]
Thank you for this gem! I have a question, what is the easiest way to do icon search? Maybe there is a built-in function?

**Comment by owaiswiz** [comment]
You can search for icons on the official website: https://tabler.io/icons

Is this what you're looking for? Or something else?

**Comment by work-leonid** [comment]
Sorry, I didn't make that clear. 

At first I thought I wanted a list of all icons so that the user could browse through them. That is, in my application I add an input where the user enters the name of the icon and somewhere nearby the matching icons are displayed. But now I realise that I don't need anything new for that. 

But suppose I want to display all available icons on one page, like https://tabler.io/icons does. How do I do that? Or just icons for a specific category.

**Comment by owaiswiz** [comment]
> But suppose I want to display all available icons on one page, like [tabler.io/icons](https://tabler.io/icons) does. How do I do that? Or just icons for a specific category.

You can't currently in an easy way. 

This library is more meant for you to consume the icon you like when building your app. 

Less for things like listing all icons or searching through icons.

However, it would be a pretty trivial thing to add I guess, and I do see it being useful for my own case later. So I might add it in the coming days.

**Comment by work-leonid** [comment]
Thank you!
